{% set name = "yte" %}
{% set version = "1.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d259548aa46c5d5ff318f3ecb1732918d1ac3c6708798767ce3823192ce1ba21

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python
  entry_points:
    - yte = yte:main

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python >=3.7
    - pip
    - uv-build
    - uv
    - argparse-dataclass >=1.0.0
    - pyyaml >=6.0,<7.0
    - dpath >=2.1,<3.0
  run:
    - python >=3.7
    - argparse-dataclass >=1.0.0
    - pyyaml >=6.0,<7.0
    - dpath >=2.1,<3.0

test:
  imports:
    - yte
  requires:
    - pip
  commands:
    - pip check
    - yte --help
    - "echo -e '?if True:\n  foo: 1' | yte"  # [not win]

about:
  home: https://github.com/koesterlab/yte
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: YAML template engine
  # The remaining entries in this section are optional, but recommended.
  description: |
    YTE is a template engine for YAML format that utilizes the YAML 
    structure in combination with Python expressions for enabling to 
    dynamically build YAML documents.
  doc_url: https://github.com/koesterlab/yte
  dev_url: https://github.com/koesterlab/yte

extra:
  recipe-maintainers:
    - johanneskoester
    - fxwiegand
